version: "3.2"
services:
    nginx:
      image: nginx
      restart: always
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./Api_food:/usr/share/nginx/html
      ports:
        - "80:80"
      links:
        - php
        - mysql

    php:
      build: ./docker/php
      restart: always
      expose:
        - "9000"
      volumes:
        - ./Api_food:/usr/share/nginx/html

      links:
        - mysql
        - redis

    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: q1o2e3e3r4
        MYSQL_DATABASE: test
 
    redis:
      image: redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - ./docker/data/redis:/data
      command: redis-server --appendonly yes
